### ISSUE TITLE
There maybe sth. wrong in lv_test_stress.h

### ISSUE THREAD

**Issue by WangZhihua1998** [littlevgl/lv_examples#1]
# There seems to be a wrong def. in it.
## `lv_test_stress_1(void)` shoud be here instead of `lv_test_object_1(void)`

**Comment by WangZhihua1998** [comment]
I think that you may just copied the file but you forgetted to rewrite it

**Comment by kisvegabor** [comment]
Hi,
Thank you! Yes, it was a copy/past issue.

I fixed it in `the dev-5.1` branch.
