### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by seyyah** [littlevgl/lv_examples#12]
TODO: There is not releases same as https://github.com/littlevgl/lvgl/releases

**Comment by kisvegabor** [comment]
There are no releases in the "lv_examples" right now because it just mainly follows the changes of "lvgl" and very rarely gets really new updates (like new apps).

**Comment by seyyah** [comment]
Because we have to old version (v5.1.1), we need the compatible version for lv_examples.

When i examined the lv_projects, I think that lv_examples versions can be like in table. If it's okay for you, i tag the releases.

| version | commit |
|-----------|------------|
| v5.1.2  | 4f9f7510b181e739cbc70d2f6b56ea657ee61967 |
| v5.1.1 | 6e005d978c0323426943d25e25082be922958506 |
| v5.1.0 | d6b40a26fd59be56e730be8be25bc4b8db8e61ef |
| v5.0.2 | 154252c24d1f31b82c27be9233e62f6b7daf91b0 |
| v5.0.1 | 0174d34e4c41ab8e0ea60f3aead02eb9145b2426 |

For example,

![image](https://user-images.githubusercontent.com/263237/47065151-b68c4a80-d1ea-11e8-963b-4874cc19d0f3.png)

- lvgl v5.1.1: https://github.com/littlevgl/lvgl/tree/522d20d9e4f896300503b3cfe744dfff4aff4aa1
- lv_examples: https://github.com/littlevgl/lv_examples/tree/6e005d978c0323426943d25e25082be922958506

So, i think that `6e005d978c0323426943d25e25082be922958506` commit for v5.1.1

**Comment by seyyah** [comment]
I create Github releases via console,

![image](https://user-images.githubusercontent.com/263237/47091307-5074e700-d22d-11e8-80fa-c1005d174084.png)

But I can't pull request. So can you add a colloborator for https://github.com/littlevgl/lv_examples?

**Comment by seyyah** [comment]
Invitation didn't come. Can you send invitation link?

**Comment by kisvegabor** [comment]
I sent the link in email

**Comment by seyyah** [comment]
It's ready

![image](https://user-images.githubusercontent.com/263237/47137100-51a22480-d2be-11e8-985b-da1d214ba616.png)

**Comment by kisvegabor** [comment]
Awesome! :)
