### ISSUE TITLE
lv_btnm_set_one_toggle() is missing

### ISSUE THREAD

**Issue by IvanShugov** [littlevgl/lv_examples#24]
I can't compile the examples with lv_btnm_set_one_toggle in lv_test_theme_1. It seems like the function doesn't exist in dev-6.0?

**Comment by embeddedt** [comment]
@IvanShugov Update to the latest `dev-6.0` version. It was added very recently.

**Comment by IvanShugov** [comment]
It should be added in the last 12 hours then? Ok, I'll update.

**Comment by embeddedt** [comment]
@IvanShugov As a reference you can make sure that HEAD points to `5565516e96bd322c217588d17c757a5749d9539e`.
