### ISSUE TITLE
Missing file - "Ticker.h" 

### ISSUE THREAD

**Issue by Uup115** [littlevgl/lv_examples#33]
Hello,

The file is missing.  As a result, "lv_test_theme" won't compile.

Best Regards

**Comment by embeddedt** [comment]
Which file is trying to include it?

**Comment by Uup115** [comment]
Hello,

Ticker.h

**Comment by kisvegabor** [comment]
But where is it required?

**Comment by Uup115** [comment]
Sorry, my mistake...  it's required for the Arduino example:  **ESP32_TFT_eSPI**.  It's not in the library.

**Comment by kisvegabor** [comment]
No problem.

**Comment by Uup115** [comment]
Should I open this issue with Littlevgl?

**Comment by kisvegabor** [comment]
If it's related to Arduino please open an issue in the Arduino repo:
https://github.com/littlevgl/lv_arduino
