### ISSUE TITLE
Root component.mk

### ISSUE THREAD

**Issue by Aiouan** [littlevgl/lv_examples#34]
In the root component.mk, shouldn't the lines:
	lv_test/lv_test_theme     \
	lv_test/lv_test_group     \
	lv_test/lv_test_group     \
be:
	lv_tests/lv_test_theme     \
	lv_tests/lv_test_group     \
	lv_tests/lv_test_group     \

I haven't really delved into makefiles before, not really ever had to, so apologies if I am missing something.

**Comment by kisvegabor** [comment]
I've fixed it, hank you!
