### ISSUE TITLE
Configuration STM32 with SSD1963

### ISSUE THREAD

**Issue by pablozizzutti** [littlevgl/lv_examples#35]
Hi there! I am new to the use of this library, and I am very excited to start it, I loved how it is made. 
I want to connect a STM32 Nucleo F746ZG board, it is a Cortex M7 processor, with a display with 800x600px SSD1963 driver, using parallel connection. I am a little dizzy in the method of configuring the MCU pins for each data. In the configuration definition, is the data port a complete port? Thank you

```c
/*------------------
 *  Parallel port
 *-----------------*/
#define LV_DRV_DISP_PAR_CS(val)          /*par_cs_set(val)*/   /*Set the Parallel port's Chip select to 'val'*/
#define LV_DRV_DISP_PAR_SLOW             /*par_slow()*/        /*Set low speed on the parallel port*/
#define LV_DRV_DISP_PAR_FAST             /*par_fast()*/        /*Set high speed on the parallel port*/
#define LV_DRV_DISP_PAR_WR_WORD(data)    /*par_wr(data)*/      /*Write a word to the parallel port*/
#define LV_DRV_DISP_PAR_WR_ARRAY(adr, n) /*par_wr_mem(adr,n)*/ /*Write 'n' bytes to Parallel ports from 'adr'*/
```

**Comment by kisvegabor** [comment]
Hi,

Let's discuss your question in the [Forum](https://forum.littlevgl.com).
We use GitHub for development-related discussions.
