### ISSUE TITLE
How to run hello world?

### ISSUE THREAD

**Issue by JimmyTheNerd** [littlevgl/lv_examples#41]
I've a basic script, based on `lv_examples/lv_tutorial/1_hello_world`:

```
/* gui.c */
#include "lvgl/lvgl.h"

int main()
{	 	 
    return 0;
}

void gui(void)
{
    lv_obj_t * scr = lv_disp_get_scr_act(NULL); /* just one line from the example */
}
```

I compile it with `gcc gui.c` and get the following error:

```
/tmp/cca5tFm7.o: In function `gui':
gui.c:(.text+0x2c): undefined reference to `lv_disp_get_scr_act'
collect2: error: ld returned 1 exit status
```

Where does `lv_disp_get_scr_act()` come from and what am I missing?

Thanks in advance!

**Comment by embeddedt** [comment]
You didn't compile any of the LittlevGL source files into your code.

**Comment by embeddedt** [comment]
Additionally, you should be running `lv_init` and registering a display before you call any other API functions.

**Comment by JimmyTheNerd** [comment]
@embeddedt I'm new to C and was expecting that all dependencies would also be compiled.

Could you please provide me the necessary lines and/or refer to the docs? I couldn't find anything in the docs, probably because it's too basic. 

Thank you!

**Comment by embeddedt** [comment]
I assume that you are doing this on a PC? In that case, I strongly recommend you start with [one of the pre-built PC simulator projects](https://docs.littlevgl.com/en/html/get-started/pc-simulator.html) instead of trying to compile it by hand like this. If you don't, you will have a lot of work before you get anything functional, and it would be a waste of effort.

**Comment by JimmyTheNerd** [comment]
Thanks @embeddedt. I'm using Raspbian on a Raspberry Pi 3B+. I'd like to test the look and feel under real conditions before going deeper. What do you recommend to run a demo app on that device?

**Comment by embeddedt** [comment]
I recommend https://github.com/littlevgl/lv_port_linux_frame_buffer.

**Comment by JimmyTheNerd** [comment]
@embeddedt Thanks! This I can compile with `make` inside the root folder and afterwards I should get `*.o`-files that are executable, correct?

**Comment by embeddedt** [comment]
`.o` files are not executable; they just contain code that needs to be linked into a final executable. The final output is a file named `demo` which is executable.

**Comment by JimmyTheNerd** [comment]
Thanks for the explanation, @embeddedt.

`make` worked, `./demo` as well, but I can't use the demo because the "window" seems to be an overlay which I can only click "through". The clicks have no impact. It's animation is running.

Please have a look at the screenshot. Any idea what's going on there? Thanks again!

![littlevgl01](https://user-images.githubusercontent.com/37954148/71989860-b1be1700-3232-11ea-989e-414e459308fe.jpg)

**Comment by embeddedt** [comment]
Ah... you didn't mention that you have a full X11 environment. In that case I suggest using the [SDL project](https://github.com/littlevgl/lv_sim_eclipse_sdl) instead.

The framebuffer project is designed to be used on systems without X11, where LittlevGL takes over the framebuffer and handles all input directly from the kernel.

**Comment by JimmyTheNerd** [comment]
Thank you, @embeddedt. I will try the SDL project. The framebuffer will be interesting in the next step, when I run it on a headless OS. Thanks again for your help! :-)
