### ISSUE TITLE
How to make a Makefile

### ISSUE THREAD

**Issue by trappedinspacetime** [littlevgl/lv_examples#45]
Awesome project! Thank you for your work.
I am on Ubuntu 16.04 platform. I want to build the examples without using IDEs. 
Is it possible?
I need an example `Makefile`
Regards.

**Comment by embeddedt** [comment]
https://github.com/littlevgl/lv_sim_eclipse_sdl has `Makefile` and `CMakeLists.txt`, neither of which require an IDE.
