### ISSUE TITLE
[rework-7] Extra LV_ASSERT_MEM_INTEGRITY calls

### ISSUE THREAD

**Issue by embeddedt** [littlevgl/lv_examples#50]
https://github.com/littlevgl/lv_examples/blob/rework-7/src/lv_ex_widgets/lv_ex_gauge/lv_ex_gauge_1.c#L13

I assume this is leftover code from debugging; do we want this left in the examples?

**Comment by kisvegabor** [comment]
Yes, thank you. I've just removed it.
6b9a553
