### ISSUE TITLE
Too many branches

### ISSUE THREAD

**Issue by C47D** [littlevgl/lv_examples#51]
@kisvegabor @embeddedt 

Some branches, are not being used nor updated (`test/no-tp` and `rework`) can we delete them?

and merge `rework-7` into `dev-7.0`?

![imagen](https://user-images.githubusercontent.com/11037705/80831244-099cd700-8bb0-11ea-8734-8343b824a396.png)

**Comment by kisvegabor** [comment]
I've removed the unused branches.
- `rework` is used in the current documentation
- `rework-7` is based on `rework` and compatible with v7. It'd be better to call it `dev-7.0` but `rework-7` is already used in many projects.

**Comment by C47D** [comment]
Thanks @kisvegabor, lv_port_esp32 is tracking rework-7 as expected.

**Comment by kisvegabor** [comment]
Great! I close this issue then.
