### ISSUE TITLE
How make it work?

### ISSUE THREAD

**Issue by prsolucoes** [littlevgl/lv_examples#9]
How make it work?

I have download lvgl and download lv_examples inside lvgl. But how i can run it into my raspberry pi 3?

In connecting to my raspberry pi 3 using SSH. I want run the examples, but there is nothing like a Makefile to build and run.

There is not documentation. The only decent tutorial that i found is a video that use eclipse and pc simulator.

Thanks.

**Comment by kisvegabor** [comment]
Continue the discussion here: https://github.com/littlevgl/lvgl/issues/380
